package TestLogger.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.actions.GeneratedActionGroup;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.workbench.action.ApplicationPlugin;

public class LoggerGroup_ActionGroup extends GeneratedActionGroup {
  public static final String ID = "TestLogger.plugin.LoggerGroup_ActionGroup";

  public LoggerGroup_ActionGroup(@Nullable ApplicationPlugin plugin) {
    super("LoggerGroup", ID, plugin);
    setIsInternal(false);
    setPopup(false);
    LoggerGroup_ActionGroup.this.addAction("TestLogger.plugin.LoggerAction_Action");
  }
}
