package TestLogger.plugin;

/*Generated by MPS */

import jetbrains.mps.plugins.applicationplugins.BaseApplicationPlugin;
import com.intellij.openapi.extensions.PluginId;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.ide.actions.Tools_ActionGroup;

public class TestLogger_ApplicationPlugin extends BaseApplicationPlugin {
  private final PluginId myId = PluginId.getId("TestLogger");

  public TestLogger_ApplicationPlugin() {
  }

  @NotNull
  public PluginId getId() {
    return myId;
  }

  public void createGroups() {
    // actions w/o parameters 
    addAction(new LoggerAction_Action());
    // groups 
    addGroup(new LoggerGroup_ActionGroup(this));
  }
  public void adjustRegularGroups() {
    insertGroupIntoAnother(LoggerGroup_ActionGroup.ID, Tools_ActionGroup.ID, null);
  }
}
